"""fix unique response_id field

Revision ID: 2dfc5b2a14dc
Revises: ecd2370c62a2
Create Date: 2025-09-26 12:34:22.831286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfc5b2a14dc'
down_revision: Union[str, Sequence[str], None] = 'ecd2370c62a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('form_responses_response_id_key'), 'form_responses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('form_responses_response_id_key'), 'form_responses', ['response_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
